.PHONY: help
help: makefile
	@tail -n +4 makefile | grep ".PHONY"


.PHONY: test
test:
	@echo "desktop tests not yet integrated"


.PHONY: build
build:
	@echo "desktop build not yet integrated"


.PHONY: clean
clean:
	@echo "desktop clean not yet integrated"
